---
name: ci

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - reopened

jobs:
  go-tests:
    uses: ./.github/actions/tests.yaml

  build:
    needs: go-tests
    uses: ./.github/actions/docker-image.yaml
